#pragma once

#include <string>
#include <cstdio>
#include <ctime>
#include <cstdarg>
#include <mutex>
#include <fstream>
#include <regex>

namespace sulla {

/**
 * Logger — structured logging with credential redaction.
 *
 * Pure utility. No business decisions.
 * Redacts tokens, passwords, and API keys from all output.
 * Writes to both console and a date-stamped log file.
 */
class Logger {
public:
    enum class Level { Trace, Debug, Info, Warn, Error };

    static Logger& instance() {
        static Logger logger;
        return logger;
    }

    void setLevel(Level level) { level_ = level; }
    void setTag(const std::string& tag) { tag_ = tag; }

    /** Set the log file directory. Filename is auto-generated by date. */
    void setLogDir(const std::string& dir) {
        logDir_ = dir;
        openLogFile();
    }

    void trace(const std::string& component, const std::string& msg) { log(Level::Trace, component, msg); }
    void debug(const std::string& component, const std::string& msg) { log(Level::Debug, component, msg); }
    void info(const std::string& component, const std::string& msg)  { log(Level::Info, component, msg); }
    void warn(const std::string& component, const std::string& msg)  { log(Level::Warn, component, msg); }
    void error(const std::string& component, const std::string& msg) { log(Level::Error, component, msg); }

    /**
     * Redact sensitive values from a string.
     * Replaces tokens, passwords, API keys with "***".
     */
    static std::string redact(const std::string& input) {
        std::string result = input;

        // Redact Bearer tokens
        result = std::regex_replace(result, std::regex(R"(Bearer\s+[A-Za-z0-9\-_\.]+)"), "Bearer ***");

        // Redact token= query params
        result = std::regex_replace(result, std::regex(R"(token=[A-Za-z0-9\-_\.]+)"), "token=***");

        // Redact api_key values
        result = std::regex_replace(result, std::regex(R"(api_key[=:]\s*[A-Za-z0-9\-_\.]+)"), "api_key=***");

        // Redact password values
        result = std::regex_replace(result, std::regex(R"("password"\s*:\s*"[^"]*")"), "\"password\":\"***\"");

        // Redact mpk_ prefixed keys
        result = std::regex_replace(result, std::regex(R"(mpk_[A-Za-z0-9\-_]+)"), "mpk_***");

        // Redact JWT tokens (three base64 segments joined by dots)
        result = std::regex_replace(result, std::regex(R"(eyJ[A-Za-z0-9\-_]+\.eyJ[A-Za-z0-9\-_]+\.[A-Za-z0-9\-_]+)"), "***jwt***");

        return result;
    }

private:
    Level       level_ = Level::Info;
    std::string tag_   = "audio-driver";
    std::string logDir_;
    std::ofstream logFile_;
    std::mutex  mutex_;

    Logger() = default;

    void log(Level level, const std::string& component, const std::string& msg) {
        if (level < level_) return;

        std::string safe = redact(msg);
        std::string timestamp = getTimestamp();
        std::string levelStr = levelToString(level);

        char line[2048];
        std::snprintf(line, sizeof(line), "%s [%s] [%s] [%s] %s",
            timestamp.c_str(), levelStr.c_str(), tag_.c_str(), component.c_str(), safe.c_str());

        std::lock_guard<std::mutex> lock(mutex_);

        // Console
        std::fprintf(level >= Level::Warn ? stderr : stdout, "%s\n", line);

        // File
        if (logFile_.is_open()) {
            logFile_ << line << "\n";
            logFile_.flush();
        }
    }

    void openLogFile() {
        if (logDir_.empty()) return;

        std::time_t now = std::time(nullptr);
        std::tm* tm = std::localtime(&now);
        char dateBuf[32];
        std::strftime(dateBuf, sizeof(dateBuf), "%Y-%m-%d", tm);

        std::string path = logDir_ + "/audio-driver-" + dateBuf + ".log";
        logFile_.open(path, std::ios::app);
    }

    static std::string getTimestamp() {
        std::time_t now = std::time(nullptr);
        std::tm* tm = std::localtime(&now);
        char buf[64];
        std::strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", tm);
        return std::string(buf);
    }

    static const char* levelToString(Level level) {
        switch (level) {
            case Level::Trace: return "TRACE";
            case Level::Debug: return "DEBUG";
            case Level::Info:  return "INFO ";
            case Level::Warn:  return "WARN ";
            case Level::Error: return "ERROR";
        }
        return "?????";
    }
};

// Convenience macros
#define SULLA_LOG_TRACE(component, msg) sulla::Logger::instance().trace(component, msg)
#define SULLA_LOG_DEBUG(component, msg) sulla::Logger::instance().debug(component, msg)
#define SULLA_LOG_INFO(component, msg)  sulla::Logger::instance().info(component, msg)
#define SULLA_LOG_WARN(component, msg)  sulla::Logger::instance().warn(component, msg)
#define SULLA_LOG_ERROR(component, msg) sulla::Logger::instance().error(component, msg)

} // namespace sulla
